version: "3"

services:
  db-postgres:
    platform: linux/x86_64
    image: postgres:15-alpine
    volumes:
      - /path/to/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: advantum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    command:
      - "postgres"
      - "-c"
      - "client_encoding=UTF8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - mysql-phpmyadmin

  db-setup-postgres:
    image: postgres:15-alpine
    depends_on:
      db-postgres:
        condition: service_healthy
    restart: "no"
    environment:
      PGPASSWORD: 123456
      PGUSER: postgres
      PGHOST: db-postgres
    command: >
      sh -c "
        sleep 5 &&
        psql -c \"
          CREATE SCHEMA IF NOT EXISTS advantum_dev;
          CREATE SCHEMA IF NOT EXISTS advantum_test;
          CREATE SCHEMA IF NOT EXISTS advantum_prom;
          CREATE SCHEMA IF NOT EXISTS warpoint_dev;
          CREATE SCHEMA IF NOT EXISTS warpoint_prom;

          GRANT ALL PRIVILEGES ON SCHEMA advantum_dev TO postgres;
          GRANT ALL PRIVILEGES ON SCHEMA advantum_test TO postgres;
          GRANT ALL PRIVILEGES ON SCHEMA advantum_prom TO postgres;
          GRANT ALL PRIVILEGES ON SCHEMA warpoint_dev TO postgres;
          GRANT ALL PRIVILEGES ON SCHEMA warpoint_prom TO postgres;
      
          GRANT CREATE ON SCHEMA advantum_dev TO postgres;
          GRANT CREATE ON SCHEMA advantum_test TO postgres;
          GRANT CREATE ON SCHEMA advantum_prom TO postgres;
          GRANT CREATE ON SCHEMA warpoint_dev TO postgres;
          GRANT CREATE ON SCHEMA warpoint_prom TO postgres;
      
          SELECT '5 schemas created successfully!' as Status;
        \"
      "
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge