-- # Транзитное время и нормы загрузок озон, транзитное время
/*
   ="select '"&A2&"','"&B2&"','"&СЖПРОБЕЛЫ(ТЕКСТ(C2;"[ч]:мм:сс"))&"' union all"
   drop ozon_transit_time car;
   truncate ozon_transit_time;
   select * from ozon_transit_time;
 */
INSERT INTO ozon_transit_time(departure, arrival, transit_time)
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:22:09' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:52:43' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:06:44' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:38:41' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','2:55:14' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:19:21' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:22:26' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:39:15' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','0:46:16' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:53:16' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_РАУМ_БУГРЫ','1:10:06' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_СПБ_ТРОИЦКИЙ','0:00:00' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:22:26' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','ЖУКОВСКИЙ_РФЦ','1:53:33' union all
select 'FRESH_MAX_МСК_АВТОГРАД','ЖУКОВСКИЙ_РФЦ','1:00:17' union all
select 'FRESH_MAX_МСК_АТРИУМ','ЖУКОВСКИЙ_РФЦ','1:00:17' union all
select 'FRESH_MAX_МСК_БЫКОВО','ЖУКОВСКИЙ_РФЦ','0:22:26' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','ЖУКОВСКИЙ_РФЦ','1:17:06' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','ЖУКОВСКИЙ_РФЦ','0:56:04' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','ЖУКОВСКИЙ_РФЦ','1:01:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','ЖУКОВСКИЙ_РФЦ','0:44:52' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','ЖУКОВСКИЙ_РФЦ','1:22:43' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','ЖУКОВСКИЙ_РФЦ','1:10:06' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','ЖУКОВСКИЙ_РФЦ','1:46:33' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','ЖУКОВСКИЙ_РФЦ','1:31:07' union all
select 'FRESH_MAX_МСК_МИТИНО','ЖУКОВСКИЙ_РФЦ','1:57:45' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','ЖУКОВСКИЙ_РФЦ','0:46:16' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','ЖУКОВСКИЙ_РФЦ','1:14:18' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','ЖУКОВСКИЙ_РФЦ','1:07:17' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','ЖУКОВСКИЙ_РФЦ','2:10:22' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','ЖУКОВСКИЙ_РФЦ','1:56:21' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','ЖУКОВСКИЙ_РФЦ','0:58:53' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','ЖУКОВСКИЙ_РФЦ','1:47:57' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','ЖУКОВСКИЙ_РФЦ','1:38:08' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','ЖУКОВСКИЙ_РФЦ','0:33:39' union all
select 'FRESH_MAX_МСК_ПУШКИНО','ЖУКОВСКИЙ_РФЦ','1:26:55' union all
select 'FRESH_MAX_МСК_РЕУТОВ','ЖУКОВСКИЙ_РФЦ','0:49:04' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','ЖУКОВСКИЙ_РФЦ','1:11:30' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','ЖУКОВСКИЙ_РФЦ','1:22:43' union all
select 'FRESH_MAX_МСК_ТРОИЦК','ЖУКОВСКИЙ_РФЦ','2:44:01' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','ЖУКОВСКИЙ_РФЦ','1:15:42' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','ЖУКОВСКИЙ_РФЦ','0:44:52' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','ЖУКОВСКИЙ_РФЦ','2:51:02' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','ЖУКОВСКИЙ_РФЦ','1:14:18' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','ЖУКОВСКИЙ_РФЦ','1:01:41' union all
select 'ПУШКИНО_2_РФЦ','ЖУКОВСКИЙ_РФЦ','1:38:08' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','ЖУКОВСКИЙ_РФЦ','4:44:35' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_DC_МСК_РЯБИНОВАЯ','1:53:33' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_АВТОГРАД','1:00:17' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_АТРИУМ','1:00:17' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_БЫКОВО','0:22:26' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЕВРОПОЛИС','1:17:06' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЕРЕМИНО','0:56:04' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:01:41' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:44:52' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:22:43' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_КРЫМСКАЯ','1:10:06' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_КУНЦЕВО','1:46:33' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:31:07' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_МИТИНО','1:57:45' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:46:16' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_МЫТИЩИ','1:14:18' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_МОСКВА_СИТИ','1:07:17' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_НОВАЯ_РИГА','2:10:22' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ОДИНЦОВО','1:56:21' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ПАРК_ХАУС','0:58:53' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ПОДОЛЬСК','1:47:57' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:38:08' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:33:39' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ПУШКИНО','1:26:55' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_РЕУТОВ','0:49:04' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_САЛАРЬЕВО','1:22:43' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ТРОИЦК','2:44:01' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:15:42' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:44:52' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_МСК_ВАРШАВСКИЙ','2:51:02' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:14:18' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:01:41' union all
select 'ЖУКОВСКИЙ_РФЦ','ПУШКИНО_2_РФЦ','1:38:08' union all
select 'ЖУКОВСКИЙ_РФЦ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:44:35' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:00:00' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','СПБ_БУГРЫ_РФЦ','24:00:00' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','СПБ_БУГРЫ_РФЦ','0:36:27' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','СПБ_БУГРЫ_РФЦ','1:28:19' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','СПБ_БУГРЫ_РФЦ','1:01:41' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','СПБ_БУГРЫ_РФЦ','0:43:27' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','СПБ_БУГРЫ_РФЦ','0:14:01' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','СПБ_БУГРЫ_РФЦ','0:50:28' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','СПБ_БУГРЫ_РФЦ','1:01:41' union all
select 'FRESH_MAX_СПБ_ЛОГОПАРК','СПБ_БУГРЫ_РФЦ','0:50:28' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','САНКТ-ПЕТЕРБУРГ_РФЦ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:54:40' union all
select 'FRESH_MAX_МСК_АВТОГРАД','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:17:06' union all
select 'FRESH_MAX_МСК_АТРИУМ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:12:54' union all
select 'FRESH_MAX_МСК_БЫКОВО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','2:10:22' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:15:42' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:18:30' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:21:19' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:14:18' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:53:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:12:54' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:49:04' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:05:53' union all
select 'FRESH_MAX_МСК_МИТИНО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:39:15' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:46:33' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:21:19' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:56:04' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','0:08:50' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:05:53' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:39:32' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:46:33' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:03:05' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:49:21' union all
select 'FRESH_MAX_МСК_ПУШКИНО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:39:32' union all
select 'FRESH_MAX_МСК_РЕУТОВ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:45:08' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:07:17' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:07:17' union all
select 'FRESH_MAX_МСК_ТРОИЦК','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:38:08' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:21:19' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:17:06' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:26:55' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:17:06' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:14:18' union all
select 'ХОРУГВИНО_КГТ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:17:06' union all
select 'ПУШКИНО_2_РФЦ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','1:52:09' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','4:05:20' union all
select 'ЖУКОВСКИЙ_РФЦ','ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','2:15:59' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_DC_МСК_РЯБИНОВАЯ','0:54:40' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_АВТОГРАД','1:17:06' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_АТРИУМ','1:12:54' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_БЫКОВО','2:10:22' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЕВРОПОЛИС','1:15:42' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЕРЕМИНО','1:18:30' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:21:19' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','1:14:18' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:53:16' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_КРЫМСКАЯ','1:12:54' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_КУНЦЕВО','0:49:04' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:05:53' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_МИТИНО','0:39:15' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:46:33' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_МЫТИЩИ','1:21:19' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_МОСКВА_СИТИ','0:56:04' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_НОВАЯ_РИГА','0:08:50' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ОДИНЦОВО','1:05:53' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ПАРК_ХАУС','1:39:32' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ПОДОЛЬСК','1:46:33' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:03:05' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:49:21' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ПУШКИНО','1:39:32' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_РЕУТОВ','1:45:08' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_САЛАРЬЕВО','1:07:17' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ТРОИЦК','1:38:08' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:21:19' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:17:06' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_МСК_ВАРШАВСКИЙ','1:26:55' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:17:06' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','ХОРУГВИНО_КГТ','1:17:06' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','ПУШКИНО_2_РФЦ','1:52:09' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:05:20' union all
select 'ПАВЛО_СЛОБОДСКОЕ_кроссдокинг','ЖУКОВСКИЙ_РФЦ','2:15:59' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:43:27' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:46:16' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','1:32:31' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:29:26' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_СПБ_ТРОИЦКИЙ','0:53:16' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:46:16' union all
select 'СПБ_БУГРЫ_РФЦ','FRESH_MAX_СПБ_ЛОГОПАРК','0:53:16' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:56:04' union all
select 'FRESH_MAX_МСК_АВТОГРАД','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:26:55' union all
select 'FRESH_АЛТУФЬЕВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:40:39' union all
select 'FRESH_MAX_МСК_АТРИУМ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:53:16' union all
select 'FRESH_MAX_МСК_БЫКОВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','2:24:24' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:58:53' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:39:15' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:10:39' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:15:42' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:51:52' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:08:41' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:56:04' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:05:53' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:56:04' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:25:31' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:53:16' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:10:06' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:05:53' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:39:32' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:59:10' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:35:03' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:22:43' union all
select 'FRESH_MAX_МСК_ПУШКИНО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:10:06' union all
select 'FRESH_MAX_МСК_РЕУТОВ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:15:42' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:49:04' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:17:06' union all
select 'FRESH_MAX_МСК_ТРОИЦК','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:49:21' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:07:17' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:05:53' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:31:07' union all
select 'FRESH_MAX_МСК_НОВЫЙ_АРБАТ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:57:29' union all
select 'FRESH_MAX_МСК_ЩУКИНО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:50:28' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:01:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:15:42' union all
select 'FRESH_MAX_МСК_КОНЬКОВО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:19:54' union all
select 'ХОРУГВИНО_КГТ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:50:28' union all
select 'ПУШКИНО_2_РФЦ','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','1:21:19' union all
select 'FRESH_MAX_МСК_МИТИНО','МО_ЧЕРНАЯ_ГРЯЗЬ_ХАБ','0:42:03';