-- # Транзитное время и нормы загрузок озон, транзитное время
/*
   ="select '"&A2&"','"&B2&"','"&СЖПРОБЕЛЫ(ТЕКСТ(C2;"[ч]:мм:сс"))&"' union all"
   drop ozon_transit_time car;
   truncate ozon_transit_time;
   select * from ozon_transit_time;
 */
INSERT INTO ozon_transit_time(departure, arrival, transit_time)
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_ВЛГ_ЗЕМЛЯЧКИ','36:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_КЗН_ГОРЬКОВСКИЙ','36:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_КЗН_ОРЕНБУРГСКИЙ','36:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_НБЧ_МЕНЗЕЛИНСКИЙ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_КДР_ПОНОМАРЕНКО','48:00:00' union all
select 'FRESH_MAX_КДР_МЕДИА_ПЛАЗА','FRESH_MAX_КДР_ПОНОМАРЕНКО','0:19:38' union all
select 'FRESH_MAX_РСТ_ЗАПАДНЫЙ','FRESH_MAX_КДР_ПОНОМАРЕНКО','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','43:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_СПБ_ТРОИЦКИЙ','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СПБ_ЛОГОПАРК','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_РСТ_ЗАПАДНЫЙ','48:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_РСТ_ШОЛОХОВО','48:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','12:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_АВТОГРАД','0:34:38' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_АТРИУМ','0:30:34' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_БЫКОВО','1:17:06' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:39:32' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:15:42' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:07:17' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:33:30' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:22:09' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_КРЫМСКАЯ','0:25:39' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_КУНЦЕВО','0:08:33' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:13:53' union all
select 'FRESH_MAX_РСТ_ШОЛОХОВО','FRESH_MAX_КДР_ПОНОМАРЕНКО','24:00:00' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:28:11' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:57:29' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_МЫТИЩИ','0:56:04' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','0:50:28' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ОДИНЦОВО','0:22:34' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:54:40' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ПОДОЛЬСК','0:56:04' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:36:02' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:51:52' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ПУШКИНО','1:22:43' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_РЕУТОВ','0:57:29' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:21:52' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ТРОИЦК','0:49:04' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:44:52' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:33:30' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_МСК_ВАРШАВСКИЙ','0:28:36' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:40:22' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','ХОРУГВИНО_КГТ','1:31:07' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','ПУШКИНО_2_РФЦ','1:19:54' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_АТРИУМ','0:43:27' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_БЫКОВО','0:56:04' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЕВРОПОЛИС','1:17:06' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЕРЕМИНО','1:38:08' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:29:43' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:19:38' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:49:04' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_КРЫМСКАЯ','0:28:02' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_КУНЦЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:28:02' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_КДР_МЕДИА_ПЛАЗА','48:00:00' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_МОСКВА_СИТИ','0:50:28' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:44:52' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_МЫТИЩИ','1:15:42' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_НОВАЯ_РИГА','1:12:54' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ОДИНЦОВО','0:47:40' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ПАРК_ХАУС','0:23:50' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ПОДОЛЬСК','0:36:27' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:01:41' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:39:15' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ПУШКИНО','1:28:19' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_РЕУТОВ','0:53:16' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_САЛАРЬЕВО','0:18:13' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ТРОИЦК','0:37:51' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:03:05' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:32:15' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_МСК_ВАРШАВСКИЙ','0:15:25' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:44:52' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:19:38' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_АВТОГРАД','0:32:15' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_БЫКОВО','0:49:04' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:18:13' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЕРЕМИНО','1:08:41' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:04:29' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:19:38' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:16:49' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_КРЫМСКАЯ','0:16:49' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_КУНЦЕВО','0:32:15' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:29:26' union all
select 'FRESH_MAX_КДР_ПОНОМАРЕНКО','FRESH_MAX_КДР_МЕДИА_ПЛАЗА','0:19:38' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:16:49' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:28:02' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_МЫТИЩИ','0:30:50' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:00:17' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ОДИНЦОВО','0:49:04' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ПАРК_ХАУС','0:29:26' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ПОДОЛЬСК','1:03:05' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:32:15' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:25:14' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ПУШКИНО','0:44:52' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_РЕУТОВ','0:25:14' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_САЛАРЬЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ТРОИЦК','1:00:17' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:15:25' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:11:13' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_МСК_ВАРШАВСКИЙ','0:23:50' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:11:13' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:19:38' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_АТРИУМ','0:54:40' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_АВТОГРАД','0:58:53' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЕВРОПОЛИС','1:10:06' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЕРЕМИНО','1:45:08' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:57:45' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:56:04' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:04:29' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_КРЫМСКАЯ','0:51:52' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_КУНЦЕВО','1:26:55' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:18:30' union all
select 'FRESH_MAX_РСТ_ЗАПАДНЫЙ','FRESH_MAX_КДР_МЕДИА_ПЛАЗА','24:00:00' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_МОСКВА_СИТИ','1:01:41' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:29:26' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_МЫТИЩИ','1:07:17' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_НОВАЯ_РИГА','2:06:10' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ОДИНЦОВО','1:39:32' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ПАРК_ХАУС','0:40:39' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ПОДОЛЬСК','1:24:07' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:36:44' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:33:39' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ПУШКИНО','1:21:19' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_РЕУТОВ','0:49:04' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_САЛАРЬЕВО','1:08:41' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ТРОИЦК','1:38:08' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:01:41' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:49:04' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_МСК_ВАРШАВСКИЙ','1:04:29' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:56:04' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:00:17' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_БЫКОВО','1:08:41' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ЕРЕМИНО','0:49:04' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:01:41' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:40:39' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:25:14' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_КРЫМСКАЯ','0:37:51' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_КУНЦЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:43:27' union all
select 'FRESH_MAX_РСТ_ШОЛОХОВО','FRESH_MAX_КДР_МЕДИА_ПЛАЗА','24:00:00' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_МОСКВА_СИТИ','0:25:14' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:46:16' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_МЫТИЩИ','0:16:49' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_НОВАЯ_РИГА','1:10:06' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ОДИНЦОВО','1:08:41' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ПАРК_ХАУС','0:58:53' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ПОДОЛЬСК','1:19:54' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:33:39' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:40:39' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ПУШКИНО','0:30:50' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_РЕУТОВ','0:35:03' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_САЛАРЬЕВО','0:53:16' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ТРОИЦК','1:18:30' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:12:37' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:28:02' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_МСК_ВАРШАВСКИЙ','0:40:39' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:16:49' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:40:39' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_АТРИУМ','0:25:14' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_АВТОГРАД','1:10:06' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_БЫКОВО','1:33:56' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:43:27' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','1:14:18' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:47:40' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_КРЫМСКАЯ','1:07:17' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_КУНЦЕВО','0:54:40' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:10:06' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_СОЧИ_ТРАНСПОРТНАЯ','72:00:00' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:54:40' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:11:30' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_МЫТИЩИ','0:40:39' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_НОВАЯ_РИГА','1:11:30' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ОДИНЦОВО','1:14:18' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ПАРК_ХАУС','1:25:31' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ПОДОЛЬСК','1:56:21' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:30:50' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:08:41' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ПУШКИНО','0:56:04' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_РЕУТОВ','1:01:41' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_САЛАРЬЕВО','1:15:42' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ТРОИЦК','1:42:20' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:51:52' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:00:17' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_МСК_ВАРШАВСКИЙ','1:17:06' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:03:05' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:05:53' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_АТРИУМ','0:57:29' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:39:15' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_АВТОГРАД','1:28:19' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_БЫКОВО','1:59:10' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','1:22:43' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:58:53' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_КРЫМСКАЯ','1:18:30' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_КУНЦЕВО','1:00:17' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:07:17' union all
select 'FRESH_DC_МСК_РЯБИНОВАЯ','FRESH_MAX_МСК_МИТИНО','0:34:54' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_МОСКВА_СИТИ','1:08:41' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:39:32' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_МЫТИЩИ','1:08:41' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_НОВАЯ_РИГА','1:12:54' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ОДИНЦОВО','1:15:42' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ПАРК_ХАУС','1:50:45' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ПОДОЛЬСК','1:56:21' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:39:15' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:33:56' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ПУШКИНО','1:21:19' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_РЕУТОВ','1:26:55' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_САЛАРЬЕВО','1:19:54' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ТРОИЦК','1:46:33' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:14:18' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:21:19' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_МСК_ВАРШАВСКИЙ','1:31:07' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:10:06' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:26:55' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_АТРИУМ','1:08:41' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ЕВРОПОЛИС','1:05:53' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_АВТОГРАД','1:31:07' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_ЕРЕМИНО','1:00:17' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_БЫКОВО','0:58:53' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:25:14' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_КРЫМСКАЯ','0:09:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_КУНЦЕВО','0:36:27' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:26:38' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_МСК_МИТИНО','0:57:29' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_МОСКВА_СИТИ','0:21:02' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:43:27' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_МЫТИЩИ','0:54:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_НОВАЯ_РИГА','1:08:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ОДИНЦОВО','0:49:04' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ПАРК_ХАУС','0:18:13' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ПОДОЛЬСК','0:47:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:56:04' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:37:51' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ПУШКИНО','1:08:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_РЕУТОВ','0:47:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_САЛАРЬЕВО','0:26:38' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ТРОИЦК','0:54:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:35:03' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:15:25' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_МСК_ВАРШАВСКИЙ','0:09:49' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:30:50' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_АТРИУМ','0:19:38' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЕВРОПОЛИС','0:46:16' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_АВТОГРАД','0:16:49' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЕРЕМИНО','1:24:07' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:26:55' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:29:26' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:29:26' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_БЫКОВО','1:03:05' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_КРЫМСКАЯ','0:21:02' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_КУНЦЕВО','0:18:13' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:23:50' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_МСК_МИТИНО','0:35:03' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:08:25' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:44:52' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_МЫТИЩИ','0:35:03' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','0:49:04' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ОДИНЦОВО','0:39:15' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:39:15' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ПОДОЛЬСК','1:15:42' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:35:03' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ПУШКИНО','0:47:40' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_РЕУТОВ','0:40:39' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ТРОИЦК','1:01:41' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:25:14' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:26:38' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_МСК_ВАРШАВСКИЙ','0:30:50' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:21:02' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_АТРИУМ','0:22:26' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:23:50' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_АВТОГРАД','0:39:15' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:03:05' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:03:05' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:09:49' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:09:49' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_БЫКОВО','0:53:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_КУНЦЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:16:49' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_МСК_МИТИНО','1:45:08' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:19:38' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:36:27' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_МЫТИЩИ','0:58:53' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:00:17' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ОДИНЦОВО','0:46:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:22:26' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ПОДОЛЬСК','0:56:04' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:53:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:30:50' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ПУШКИНО','1:12:54' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_РЕУТОВ','0:44:52' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:23:50' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ТРОИЦК','0:50:28' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:33:39' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:12:37' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_МСК_ВАРШАВСКИЙ','0:12:37' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:29:26' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_АТРИУМ','0:22:26' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:39:15' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_АВТОГРАД','0:22:26' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:19:54' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:24:07' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:23:50' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:30:50' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:30:50' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_БЫКОВО','1:28:19' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:19:38' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_МСК_МИТИНО','0:46:16' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:22:26' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:17:06' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_МЫТИЩИ','1:00:17' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_НОВАЯ_РИГА','0:42:03' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ОДИНЦОВО','0:25:14' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ПАРК_ХАУС','0:56:04' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ПОДОЛЬСК','1:05:53' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:29:26' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:11:30' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ПУШКИНО','1:15:42' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_РЕУТОВ','1:19:54' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_САЛАРЬЕВО','0:25:14' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ТРОИЦК','0:51:52' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:46:16' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:36:27' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_МСК_ВАРШАВСКИЙ','0:37:51' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:39:15' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_АТРИУМ','0:32:15' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:49:04' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_АВТОГРАД','0:37:51' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЕРЕМИНО','1:11:30' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:58:53' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:19:38' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_КРЫМСКАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:23:50' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_БЫКОВО','1:22:43' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_МСК_МИТИНО','0:44:52' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:19:38' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:51:52' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_МЫТИЩИ','1:11:30' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_НОВАЯ_РИГА','1:10:06' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ОДИНЦОВО','0:30:50' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ПАРК_ХАУС','0:50:28' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ПОДОЛЬСК','1:08:41' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:44:52' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:46:16' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ПУШКИНО','1:24:07' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_РЕУТОВ','1:00:17' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_САЛАРЬЕВО','0:21:02' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ТРОИЦК','0:46:16' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:43:27' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:29:26' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_МСК_ВАРШАВСКИЙ','0:22:26' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:39:15' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_АТРИУМ','0:28:02' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:42:03' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_АВТОГРАД','0:32:15' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ЕРЕМИНО','1:26:55' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:07:17' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:22:26' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_КРЫМСКАЯ','0:22:26' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_КУНЦЕВО','0:18:13' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_АТРИУМ','0:43:27' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_БЫКОВО','1:45:08' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЕРЕМИНО','1:01:41' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:57:29' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_КРЫМСКАЯ','0:51:52' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_КУНЦЕВО','0:28:02' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:40:39' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:36:27' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:25:31' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_МЫТИЩИ','0:53:16' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_НОВАЯ_РИГА','0:30:50' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ОДИНЦОВО','0:43:27' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ПАРК_ХАУС','1:18:30' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ПОДОЛЬСК','1:26:55' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:21:02' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:21:19' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ПУШКИНО','1:04:29' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_РЕУТОВ','1:10:06' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_САЛАРЬЕВО','0:49:04' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ТРОИЦК','1:15:42' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:00:17' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:54:40' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_МСК_ВАРШАВСКИЙ','1:11:30' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:43:27' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:57:29' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_АВТОГРАД','1:01:41' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:47:40' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:47:40' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:28:02' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_АТРИУМ','0:30:50' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_БЫКОВО','0:29:26' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ЕРЕМИНО','1:24:07' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:46:16' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_КРЫМСКАЯ','0:37:51' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_КУНЦЕВО','1:18:30' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:11:30' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:49:04' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_МЫТИЩИ','0:46:16' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:50:45' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ОДИНЦОВО','1:29:43' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ПАРК_ХАУС','0:28:02' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ПОДОЛЬСК','1:15:42' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:05:53' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:12:37' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ПУШКИНО','0:56:04' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_РЕУТОВ','0:22:26' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_САЛАРЬЕВО','1:00:17' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ТРОИЦК','1:22:43' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:36:27' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:29:26' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_МСК_ВАРШАВСКИЙ','0:53:16' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:46:16' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_АВТОГРАД','0:46:16' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:44:52' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:32:31' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:50:28' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_МСК_МИТИНО','0:39:15' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_АТРИУМ','0:36:27' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_БЫКОВО','1:10:06' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЕРЕМИНО','0:54:40' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:58:53' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_КРЫМСКАЯ','0:53:16' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_КУНЦЕВО','0:58:53' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:51:52' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:40:39' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:14:18' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ОДИНЦОВО','1:17:06' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ПАРК_ХАУС','0:58:53' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ПОДОЛЬСК','1:45:08' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:37:51' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:42:03' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ПУШКИНО','0:22:26' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_РЕУТОВ','0:35:03' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_САЛАРЬЕВО','1:19:54' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ТРОИЦК','1:46:33' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:36:27' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:50:28' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_МСК_ВАРШАВСКИЙ','1:08:41' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:32:15' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:58:53' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_АВТОГРАД','1:15:42' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:18:13' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:00:17' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:46:16' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_МСК_МИТИНО','0:51:52' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:46:16' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_МЫТИЩИ','0:32:15' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_АТРИУМ','0:11:13' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_БЫКОВО','0:56:04' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЕРЕМИНО','1:04:29' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:21:02' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_КРЫМСКАЯ','0:16:49' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_КУНЦЕВО','0:29:26' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:28:02' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_НОВАЯ_РИГА','0:58:53' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ОДИНЦОВО','0:44:52' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ПАРК_ХАУС','0:32:15' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ПОДОЛЬСК','1:11:30' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:26:38' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:29:26' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ПУШКИНО','0:49:04' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_РЕУТОВ','0:39:15' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_САЛАРЬЕВО','0:33:39' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ТРОИЦК','1:00:17' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:18:13' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:14:01' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_МСК_ВАРШАВСКИЙ','0:28:02' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:14:01' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:21:02' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_АВТОГРАД','0:35:03' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:21:02' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:01:41' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:14:01' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_МСК_МИТИНО','0:30:50' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:35:03' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_МЫТИЩИ','1:21:19' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_АТРИУМ','1:10:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_БЫКОВО','2:15:59' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЕРЕМИНО','1:29:43' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','1:17:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_КРЫМСКАЯ','1:10:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_КУНЦЕВО','0:44:52' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:00:17' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ОДИНЦОВО','1:01:41' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ПАРК_ХАУС','1:35:20' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ПОДОЛЬСК','1:43:44' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:51:52' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:50:45' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ПУШКИНО','1:36:44' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_РЕУТОВ','1:42:20' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_САЛАРЬЕВО','1:03:05' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ТРОИЦК','1:35:20' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:10:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:15:42' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_МСК_ВАРШАВСКИЙ','1:15:42' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:10:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:17:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_АВТОГРАД','1:17:06' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЕВРОПОЛИС','1:07:17' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:18:30' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:53:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_МСК_МИТИНО','0:49:04' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:43:44' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_МОСКВА_СИТИ','0:58:53' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_НОВАЯ_РИГА','1:00:17' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_МЫТИЩИ','1:19:54' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_АТРИУМ','0:47:40' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_БЫКОВО','1:38:08' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЕРЕМИНО','1:31:07' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:50:28' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_КРЫМСКАЯ','0:47:40' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_КУНЦЕВО','0:26:38' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:29:26' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ПАРК_ХАУС','1:07:17' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ПОДОЛЬСК','1:17:06' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:47:40' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:22:43' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ПУШКИНО','1:33:56' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_РЕУТОВ','1:36:44' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_САЛАРЬЕВО','0:32:15' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ТРОИЦК','0:51:52' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:01:41' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:57:29' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_МСК_ВАРШАВСКИЙ','0:58:53' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:57:29' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:50:28' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_АВТОГРАД','0:50:28' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:46:16' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:17:06' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:44:52' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_МСК_МИТИНО','0:25:14' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:28:19' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:42:03' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ОДИНЦОВО','1:08:41' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_НОВАЯ_РИГА','1:33:56' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_МЫТИЩИ','0:57:29' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_АТРИУМ','0:36:27' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_БЫКОВО','0:40:39' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЕРЕМИНО','1:36:44' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:16:49' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_КРЫМСКАЯ','0:23:50' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_КУНЦЕВО','0:54:40' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:35:03' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ПОДОЛЬСК','0:51:52' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:21:19' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:21:02' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ПУШКИНО','1:11:30' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_РЕУТОВ','0:35:03' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_САЛАРЬЕВО','0:37:51' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ТРОИЦК','0:58:53' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:49:04' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:32:15' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_МСК_ВАРШАВСКИЙ','0:29:26' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:39:15' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:23:50' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_АВТОГРАД','0:22:26' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЕВРОПОЛИС','1:00:17' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:47:57' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:40:39' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_МСК_МИТИНО','0:40:39' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:26:38' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_МОСКВА_СИТИ','0:40:39' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ПАРК_ХАУС','0:54:40' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ОДИНЦОВО','1:19:54' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_НОВАЯ_РИГА','1:40:56' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_МЫТИЩИ','1:49:21' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_АТРИУМ','1:05:53' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_БЫКОВО','1:24:07' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЕРЕМИНО','2:11:47' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:51:52' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_КРЫМСКАЯ','0:57:29' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_КУНЦЕВО','1:12:54' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:03:05' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:33:56' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:11:30' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ПУШКИНО','1:57:45' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_РЕУТОВ','1:22:43' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_САЛАРЬЕВО','0:56:04' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ТРОИЦК','0:35:03' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:36:44' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:00:17' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_МСК_ВАРШАВСКИЙ','0:47:40' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:24:07' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:51:52' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_АВТОГРАД','0:37:51' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЕВРОПОЛИС','1:46:33' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:14:18' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:18:30' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_МСК_МИТИНО','1:21:19' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:07:17' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_МОСКВА_СИТИ','1:17:06' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ПОДОЛЬСК','1:40:56' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ПАРК_ХАУС','1:17:06' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ОДИНЦОВО','0:57:29' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_НОВАЯ_РИГА','0:54:40' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_МЫТИЩИ','0:35:03' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_АТРИУМ','0:40:39' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_БЫКОВО','1:28:19' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЕРЕМИНО','0:40:39' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:50:28' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_КРЫМСКАЯ','0:44:52' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_КУНЦЕВО','0:39:15' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:53:16' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:00:17' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ПУШКИНО','0:47:40' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_РЕУТОВ','0:53:16' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_САЛАРЬЕВО','1:00:17' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ТРОИЦК','1:25:31' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:44:52' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:49:04' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_МСК_ВАРШАВСКИЙ','0:54:40' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:36:27' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:50:28' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_АВТОГРАД','1:12:54' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:30:50' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:33:39' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:28:02' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_МСК_МИТИНО','0:49:04' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:03:05' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:30:50' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:03:05' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ПОДОЛЬСК','1:08:41' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:22:26' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ОДИНЦОВО','1:24:07' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:50:45' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_МЫТИЩИ','0:40:39' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_АТРИУМ','0:21:02' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_БЫКОВО','0:35:03' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:19:54' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:39:15' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_КРЫМСКАЯ','0:30:50' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_КУНЦЕВО','1:11:30' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:04:29' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ПУШКИНО','0:53:16' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_РЕУТОВ','0:16:49' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:53:16' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ТРОИЦК','1:15:42' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:30:50' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:22:26' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_МСК_ВАРШАВСКИЙ','0:49:04' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:32:15' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:39:15' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_АВТОГРАД','0:37:51' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:42:03' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:29:43' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:43:27' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_МСК_МИТИНО','0:37:51' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:09:49' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:39:15' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:54:40' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:50:28' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ПОДОЛЬСК','1:57:45' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ПАРК_ХАУС','1:10:06' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ОДИНЦОВО','1:33:56' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_НОВАЯ_РИГА','1:35:20' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_МЫТИЩИ','0:21:02' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_АТРИУМ','1:00:17' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_БЫКОВО','1:19:54' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЕРЕМИНО','1:08:41' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','1:14:18' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_КРЫМСКАЯ','1:12:54' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_КУНЦЕВО','1:15:42' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:25:31' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_РЕУТОВ','0:46:16' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_САЛАРЬЕВО','1:36:44' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ТРОИЦК','2:03:22' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:49:04' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:11:30' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_МСК_ВАРШАВСКИЙ','1:24:07' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:49:04' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:14:18' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_АВТОГРАД','1:28:19' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:30:50' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:17:06' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:03:05' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_МСК_МИТИНО','0:30:50' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:57:29' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_МОСКВА_СИТИ','1:05:53' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ПУШКИНО','0:46:16' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:19:38' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:56:04' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ПОДОЛЬСК','1:14:18' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ПАРК_ХАУС','0:35:03' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ОДИНЦОВО','1:42:20' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:40:56' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_МЫТИЩИ','0:33:39' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_АТРИУМ','0:26:38' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_БЫКОВО','0:49:04' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЕРЕМИНО','1:12:54' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:51:52' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_КРЫМСКАЯ','0:43:27' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_КУНЦЕВО','1:21:19' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:29:43' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_САЛАРЬЕВО','1:05:53' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ТРОИЦК','1:28:19' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:26:38' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:33:39' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_МСК_ВАРШАВСКИЙ','1:04:29' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:25:14' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:51:52' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_АВТОГРАД','0:50:28' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:35:03' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:22:43' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:53:16' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_МСК_МИТИНО','0:43:27' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:23:50' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:43:27' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_РЕУТОВ','0:49:04' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ПУШКИНО','0:47:40' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:26:38' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ПОДОЛЬСК','1:26:55' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ПАРК_ХАУС','0:43:27' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ОДИНЦОВО','0:54:40' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_НОВАЯ_РИГА','0:54:40' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_МЫТИЩИ','0:35:03' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_АТРИУМ','0:16:49' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_БЫКОВО','1:01:41' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЕРЕМИНО','1:01:41' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:32:15' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_КРЫМСКАЯ','0:25:14' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_КУНЦЕВО','0:26:38' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:26:38' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_САЛАРЬЕВО','0:44:52' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ТРОИЦК','1:08:41' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:28:02' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:25:14' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_МСК_ВАРШАВСКИЙ','0:35:03' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:16:49' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:32:15' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_АВТОГРАД','0:51:52' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:18:13' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:57:29' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:07:01' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_МСК_МИТИНО','1:17:06' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:44:52' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:08:25' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_РЕУТОВ','1:11:30' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ПУШКИНО','1:35:20' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:56:04' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:50:28' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ПОДОЛЬСК','0:51:52' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ПАРК_ХАУС','0:42:03' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ОДИНЦОВО','0:36:27' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_НОВАЯ_РИГА','1:03:05' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_МЫТИЩИ','1:19:54' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_АТРИУМ','0:35:03' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_БЫКОВО','1:17:06' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЕРЕМИНО','1:29:43' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:29:26' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_КРЫМСКАЯ','0:26:38' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_КУНЦЕВО','0:23:50' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:18:13' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ТРОИЦК','0:32:15' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:50:28' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_МСК_ВАРШАВСКИЙ','0:35:03' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:58:53' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:29:26' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_АВТОГРАД','0:25:14' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЕВРОПОЛИС','0:56:04' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:19:54' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:36:27' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_МСК_МИТИНО','1:22:43' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:04:29' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_МОСКВА_СИТИ','0:36:27' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_САЛАРЬЕВО','0:36:27' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_РЕУТОВ','1:31:07' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ПУШКИНО','2:08:58' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:17:06' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:21:19' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ПОДОЛЬСК','0:40:39' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ПАРК_ХАУС','1:03:05' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ОДИНЦОВО','0:51:52' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_НОВАЯ_РИГА','1:35:20' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_МЫТИЩИ','1:50:45' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_АТРИУМ','1:03:05' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_БЫКОВО','1:38:08' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЕРЕМИНО','1:57:45' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:56:04' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_КРЫМСКАЯ','0:53:16' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_КУНЦЕВО','0:56:04' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:46:16' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:19:54' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:03:05' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_МСК_ВАРШАВСКИЙ','0:53:16' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:15:42' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:56:04' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_АВТОГРАД','0:43:27' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЕВРОПОЛИС','1:25:31' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:49:21' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:08:41' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_МСК_МИТИНО','0:28:02' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:22:43' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_МОСКВА_СИТИ','1:03:05' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ТРОИЦК','1:24:07' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_САЛАРЬЕВО','1:00:17' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_РЕУТОВ','0:25:14' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ПУШКИНО','0:39:15' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:30:50' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:47:40' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ПОДОЛЬСК','1:35:20' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ПАРК_ХАУС','0:46:16' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ОДИНЦОВО','1:18:30' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:12:54' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_МЫТИЩИ','0:36:27' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_АТРИУМ','0:22:26' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_БЫКОВО','0:56:04' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЕРЕМИНО','1:12:54' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:37:51' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_КРЫМСКАЯ','0:35:03' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_КУНЦЕВО','0:42:03' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:42:03' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:26:38' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_МСК_ВАРШАВСКИЙ','0:43:27' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:07:01' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:37:51' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_АВТОГРАД','1:04:29' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:12:37' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:14:18' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:26:38' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_МСК_МИТИНО','1:14:18' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:35:03' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:28:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:25:14' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ТРОИЦК','0:58:53' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:35:03' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_РЕУТОВ','0:35:03' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ПУШКИНО','1:03:05' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:21:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:47:40' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ПОДОЛЬСК','1:00:17' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:21:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ОДИНЦОВО','0:53:16' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:14:18' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_МЫТИЩИ','0:50:28' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_АТРИУМ','0:11:13' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_БЫКОВО','0:46:16' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:21:19' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:14:01' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_КРЫМСКАЯ','0:15:25' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_КУНЦЕВО','0:37:51' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:28:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_МСК_ВАРШАВСКИЙ','0:21:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:21:02' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:14:01' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_АВТОГРАД','0:29:26' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:33:39' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:14:18' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:28:02' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_МСК_МИТИНО','1:01:41' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:26:38' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:21:02' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:22:26' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:43:27' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ТРОИЦК','0:46:16' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_САЛАРЬЕВО','0:26:38' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_РЕУТОВ','1:00:17' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ПУШКИНО','1:36:44' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:46:16' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:10:06' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ПОДОЛЬСК','0:39:15' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ПАРК_ХАУС','0:30:50' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ОДИНЦОВО','0:56:04' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:21:19' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_МЫТИЩИ','1:22:43' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_АТРИУМ','0:33:39' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_БЫКОВО','1:05:53' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЕРЕМИНО','1:46:33' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:11:13' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_КРЫМСКАЯ','0:18:13' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_КУНЦЕВО','0:42:03' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:22:26' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:36:27' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:11:13' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_АВТОГРАД','0:08:25' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:51:52' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:38:08' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:36:27' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_МСК_МИТИНО','1:11:30' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:51:52' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:32:15' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_МСК_ВАРШАВСКИЙ','0:36:27' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:16:49' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:08:25' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ТРОИЦК','1:14:18' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_САЛАРЬЕВО','0:47:40' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_РЕУТОВ','0:23:50' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ПУШКИНО','0:49:04' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:32:15' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:36:27' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ПОДОЛЬСК','1:33:56' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ПАРК_ХАУС','0:47:40' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ОДИНЦОВО','0:56:04' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:05:53' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_МЫТИЩИ','0:36:27' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_АТРИУМ','0:12:37' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_БЫКОВО','0:56:04' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ЕРЕМИНО','1:08:41' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','0:29:26' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_КРЫМСКАЯ','0:25:14' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_КУНЦЕВО','0:39:15' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:37:51' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','0:29:26' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_АВТОГРАД','0:43:27' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:19:38' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:04:29' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:21:02' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_МСК_МИТИНО','0:28:02' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:35:03' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_МОСКВА_СИТИ','0:22:26' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_БЫКОВО','0:58:53' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','0:25:14' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_КРЫМСКАЯ','0:09:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_КУНЦЕВО','0:36:27' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','0:26:38' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_МСК_МИТИНО','0:47:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_МОСКВА_СИТИ','0:21:02' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЛЮБЕРЦЫ','0:43:27' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_МЫТИЩИ','0:54:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_НОВАЯ_РИГА','1:08:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ОДИНЦОВО','0:49:04' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ПАРК_ХАУС','0:18:13' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ПОДОЛЬСК','0:47:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','0:56:04' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','0:37:51' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ПУШКИНО','1:08:41' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_РЕУТОВ','0:47:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_САЛАРЬЕВО','0:26:38' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ТРОИЦК','0:54:40' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:35:03' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','0:15:25' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_МСК_ВАРШАВСКИЙ','0:09:49' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','0:30:50' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_АТРИУМ','0:19:38' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЕВРОПОЛИС','0:46:16' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_АВТОГРАД','0:16:49' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЕРЕМИНО','1:24:07' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:26:55' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','1:15:42' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:22:26' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:19:38' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','0:46:16' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_СПБ_ТРОИЦКИЙ','0:39:15' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:22:26' union all
select 'FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','FRESH_MAX_СПБ_ЛОГОПАРК','0:39:15' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','1:17:06' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:35:03' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','1:22:43' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','1:50:45' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_СПБ_ТРОИЦКИЙ','0:46:16' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:35:03' union all
select 'FRESH_MAX_СПБ_ВОЛХОНСКИЙ','FRESH_MAX_СПБ_ЛОГОПАРК','0:46:16' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','0:39:15' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:21:02' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:25:14' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','1:03:05' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_СПБ_ТРОИЦКИЙ','0:22:26' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:00:00' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ','FRESH_MAX_СПБ_ЛОГОПАРК','0:22:26' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:26:38' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','1:29:43' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:19:38' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','0:36:27' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_СПБ_ТРОИЦКИЙ','0:53:16' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:26:38' union all
select 'FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','FRESH_MAX_СПБ_ЛОГОПАРК','0:53:16' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:28:02' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:49:04' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','1:31:07' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:32:15' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_СПБ_ТРОИЦКИЙ','0:54:40' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:49:04' union all
select 'FRESH_MAX_СПБ_РАУМ_БУГРЫ','FRESH_MAX_СПБ_ЛОГОПАРК','0:54:40' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_РАУМ_БУГРЫ','1:10:06' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:54:40' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:23:50' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','0:43:27' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:40:39' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','0:23:50' union all
select 'FRESH_СПБ_ТРОИЦКИЙ','FRESH_MAX_СПБ_ЛОГОПАРК','0:00:00' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_ВОЛХОНСКИЙ','0:39:15' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_БЕСТУЖЕВСКИЙ','0:21:02' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_МЕБЕЛЬНАЯ','0:25:14' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_РАУМ_БУГРЫ','1:03:05' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_СПБ_ТРОИЦКИЙ','0:22:26' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_ЛИГОВСКИЙ','0:00:00' union all
select 'FRESH_MAX_СПБ_ЛИГОВСКИЙ_2','FRESH_MAX_СПБ_ЛОГОПАРК','0:22:26' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_МСК_МИТИНО','1:17:06' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_МСК_МИТИНО','0:50:28' union all
select 'FRESH_MAX_РСТ_ЗАПАДНЫЙ','FRESH_MAX_РСТ_ШОЛОХОВО','0:29:26' union all
select 'FRESH_MAX_РСТ_ШОЛОХОВО','FRESH_MAX_РСТ_ЗАПАДНЫЙ','0:29:26' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','FRESH_MAX_МСК_МИТИНО','0:51:52' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','FRESH_MAX_МСК_МИТИНО','1:04:29' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','FRESH_MAX_МСК_МИТИНО','0:40:39' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','FRESH_MAX_МСК_МИТИНО','0:51:52' union all
select 'FRESH_MAX_КЗН_ГОРЬКОВСКИЙ','FRESH_MAX_КЗН_ОРЕНБУРГСКИЙ','0:28:02' union all
select 'FRESH_MAX_КЗН_ОРЕНБУРГСКИЙ','FRESH_MAX_КЗН_ГОРЬКОВСКИЙ','0:28:02' union all
select 'FRESH_MAX_КЗН_ОРЕНБУРГСКИЙ','FRESH_MAX_НБЧ_МЕНЗЕЛИНСКИЙ','24:00:00' union all
select 'FRESH_MAX_КЗН_ГОРЬКОВСКИЙ','FRESH_MAX_НБЧ_МЕНЗЕЛИНСКИЙ','24:00:00' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_БЫКОВО','2:18:47' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:26:55' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_КРЫМСКАЯ','1:49:21' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_КУНЦЕВО','1:26:55' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:42:20' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_МИТИНО','1:31:07' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_МОСКВА_СИТИ','1:39:32' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:47:57' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_МЫТИЩИ','1:22:43' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:19:54' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ОДИНЦОВО','2:04:46' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ПАРК_ХАУС','2:01:58' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ПОДОЛЬСК','2:37:01' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:07:17' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:45:08' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ПУШКИНО','1:38:08' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_РЕУТОВ','1:49:21' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_САЛАРЬЕВО','1:47:57' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ТРОИЦК','2:14:35' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','1:36:44' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:36:44' union all
select 'ХОРУГВИНО_КГТ','FRESH_МСК_ВАРШАВСКИЙ','1:54:57' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:28:19' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_АТРИУМ','1:28:19' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЕВРОПОЛИС','1:26:55' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_АВТОГРАД','2:00:34' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЕРЕМИНО','0:49:04' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','0:35:03' union all
select 'ХОРУГВИНО_КГТ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:56:21' union all
select 'FRESH_MAX_МСК_БЫКОВО','ХОРУГВИНО_КГТ','2:18:47' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','ХОРУГВИНО_КГТ','1:26:55' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','ХОРУГВИНО_КГТ','1:49:21' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','ХОРУГВИНО_КГТ','1:26:55' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','ХОРУГВИНО_КГТ','1:42:20' union all
select 'FRESH_MAX_МСК_МИТИНО','ХОРУГВИНО_КГТ','1:31:07' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','ХОРУГВИНО_КГТ','1:39:32' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','ХОРУГВИНО_КГТ','1:47:57' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','ХОРУГВИНО_КГТ','1:22:43' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','ХОРУГВИНО_КГТ','1:19:54' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','ХОРУГВИНО_КГТ','2:04:46' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','ХОРУГВИНО_КГТ','2:01:58' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','ХОРУГВИНО_КГТ','2:37:01' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','ХОРУГВИНО_КГТ','1:07:17' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','ХОРУГВИНО_КГТ','1:45:08' union all
select 'FRESH_MAX_МСК_ПУШКИНО','ХОРУГВИНО_КГТ','1:38:08' union all
select 'FRESH_MAX_МСК_РЕУТОВ','ХОРУГВИНО_КГТ','1:49:21' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','ХОРУГВИНО_КГТ','1:29:43' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','ХОРУГВИНО_КГТ','1:47:57' union all
select 'FRESH_MAX_МСК_ТРОИЦК','ХОРУГВИНО_КГТ','2:14:35' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','ХОРУГВИНО_КГТ','1:36:44' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','ХОРУГВИНО_КГТ','1:36:44' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','ХОРУГВИНО_КГТ','1:54:57' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','ХОРУГВИНО_КГТ','1:28:19' union all
select 'FRESH_MAX_МСК_АТРИУМ','ХОРУГВИНО_КГТ','1:28:19' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','ХОРУГВИНО_КГТ','1:26:55' union all
select 'FRESH_MAX_МСК_АВТОГРАД','ХОРУГВИНО_КГТ','2:00:34' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','ХОРУГВИНО_КГТ','0:49:04' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','ХОРУГВИНО_КГТ','0:35:03' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','ХОРУГВИНО_КГТ','1:56:21' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_БЫКОВО','1:39:32' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','1:14:18' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_КРЫМСКАЯ','1:19:54' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_КУНЦЕВО','1:26:55' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','1:36:44' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_МИТИНО','1:17:06' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_МОСКВА_СИТИ','1:18:30' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЛЮБЕРЦЫ','1:10:06' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_МЫТИЩИ','0:33:39' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_НОВАЯ_РИГА','1:46:33' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ОДИНЦОВО','1:43:44' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ПАРК_ХАУС','1:24:07' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ПОДОЛЬСК','2:17:23' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','1:03:05' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','1:07:17' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ПУШКИНО','0:14:01' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_РЕУТОВ','0:58:53' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_САЛАРЬЕВО','1:47:57' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ТРОИЦК','2:14:35' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ТЮМЕНСКИЙ','0:57:29' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','1:15:42' union all
select 'ПУШКИНО_2_РФЦ','FRESH_МСК_ВАРШАВСКИЙ','1:32:31' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','1:00:17' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_АТРИУМ','1:11:30' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЕВРОПОЛИС','0:42:03' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_АВТОГРАД','1:39:32' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЕРЕМИНО','1:19:54' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','1:35:20' union all
select 'ПУШКИНО_2_РФЦ','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','1:25:31' union all
select 'FRESH_MAX_МСК_БЫКОВО','ПУШКИНО_2_РФЦ','1:39:32' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','ПУШКИНО_2_РФЦ','1:14:18' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','ПУШКИНО_2_РФЦ','1:19:54' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','ПУШКИНО_2_РФЦ','1:26:55' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','ПУШКИНО_2_РФЦ','1:36:44' union all
select 'FRESH_MAX_МСК_МИТИНО','ПУШКИНО_2_РФЦ','1:17:06' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','ПУШКИНО_2_РФЦ','1:18:30' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','ПУШКИНО_2_РФЦ','1:10:06' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','ПУШКИНО_2_РФЦ','0:33:39' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','ПУШКИНО_2_РФЦ','1:46:33' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','ПУШКИНО_2_РФЦ','1:43:44' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','ПУШКИНО_2_РФЦ','1:24:07' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','ПУШКИНО_2_РФЦ','2:17:23' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','ПУШКИНО_2_РФЦ','1:03:05' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','ПУШКИНО_2_РФЦ','1:07:17' union all
select 'FRESH_MAX_МСК_ПУШКИНО','ПУШКИНО_2_РФЦ','0:14:01' union all
select 'FRESH_MAX_МСК_РЕУТОВ','ПУШКИНО_2_РФЦ','0:58:53' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','ПУШКИНО_2_РФЦ','1:11:30' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','ПУШКИНО_2_РФЦ','1:47:57' union all
select 'FRESH_MAX_МСК_ТРОИЦК','ПУШКИНО_2_РФЦ','2:14:35' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','ПУШКИНО_2_РФЦ','0:57:29' union all
select 'FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','ПУШКИНО_2_РФЦ','1:15:42' union all
select 'FRESH_МСК_ВАРШАВСКИЙ','ПУШКИНО_2_РФЦ','1:32:31' union all
select 'FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','ПУШКИНО_2_РФЦ','1:00:17' union all
select 'FRESH_MAX_МСК_АТРИУМ','ПУШКИНО_2_РФЦ','1:11:30' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','ПУШКИНО_2_РФЦ','0:42:03' union all
select 'FRESH_MAX_МСК_АВТОГРАД','ПУШКИНО_2_РФЦ','1:39:32' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','ПУШКИНО_2_РФЦ','1:19:54' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','ПУШКИНО_2_РФЦ','1:35:20' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','ПУШКИНО_2_РФЦ','1:25:31' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_АВТОГРАД','3:42:54' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_АТРИУМ','3:30:17' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_БЫКОВО','4:40:22' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЕВРОПОЛИС','3:48:30' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЕРЕМИНО','3:54:07' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЗЕЛЕНОГРАД','3:13:27' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','3:38:41' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','3:16:16' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_КРЫМСКАЯ','3:31:41' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_КУНЦЕВО','3:09:15' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','3:21:52' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_МИТИНО','3:03:39' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_МОСКВА_СИТИ','3:27:29' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЛЮБЕРЦЫ','4:31:58' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_МЫТИЩИ','3:48:30' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_НОВАЯ_РИГА','2:44:01' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ОДИНЦОВО','3:20:28' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ПАРК_ХАУС','4:02:31' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ПОДОЛЬСК','4:17:57' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','3:16:16' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ПРИВОЛЬНАЯ','4:26:21' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ПУШКИНО','4:03:56' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_РЕУТОВ','4:03:56' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_САЛАРЬЕВО','3:30:17' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ТРОИЦК','3:54:07' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ТЮМЕНСКИЙ','4:08:08' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ШАРИКОПОДШИПНИКОВСКАЯ','4:22:09' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_МСК_ВАРШАВСКИЙ','3:52:43' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_ЭЛЕКТРОЗАВОДСКАЯ','4:06:44' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР_2','3:38:41' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','ХОРУГВИНО_КГТ','2:55:14' union all
select 'FRESH_MAX_ТВЕРЬ_КАЛИНИНА','ПУШКИНО_2_РФЦ','4:19:21' union all
select 'FRESH_MAX_МСК_АВТОГРАД','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:42:54' union all
select 'FRESH_MAX_МСК_АТРИУМ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:30:17' union all
select 'FRESH_MAX_МСК_БЫКОВО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:40:22' union all
select 'FRESH_MAX_МСК_ЕВРОПОЛИС','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:48:30' union all
select 'FRESH_MAX_МСК_ЕРЕМИНО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:54:07' union all
select 'FRESH_MAX_МСК_ЗЕЛЕНОГРАД','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:13:27' union all
select 'FRESH_MAX_МСК_КАШИРСКИЙ_ДВОР','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:38:41' union all
select 'FRESH_MAX_МСК_КРАСНАЯ_ПРЕСНЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:16:16' union all
select 'FRESH_MAX_МСК_КРЫМСКАЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:31:41' union all
select 'FRESH_MAX_МСК_КУНЦЕВО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:09:15' union all
select 'FRESH_MAX_МСК_ЛОБАЧЕВСКОГО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:21:52' union all
select 'FRESH_MAX_МСК_МИТИНО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:03:39' union all
select 'FRESH_MAX_МСК_МОСКВА_СИТИ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:27:29' union all
select 'FRESH_MAX_МСК_ЛЮБЕРЦЫ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:31:58' union all
select 'FRESH_MAX_МСК_МЫТИЩИ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:48:30' union all
select 'FRESH_MAX_МСК_НОВАЯ_РИГА','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','2:44:01' union all
select 'FRESH_MAX_МСК_ОДИНЦОВО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:20:28' union all
select 'FRESH_MAX_МСК_ПАРК_ХАУС','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:02:31' union all
select 'FRESH_MAX_МСК_ПОДОЛЬСК','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:17:57' union all
select 'FRESH_MAX_МСК_ПРАВОБЕРЕЖНЫЙ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:16:16' union all
select 'FRESH_MAX_МСК_ПРИВОЛЬНАЯ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:26:21' union all
select 'FRESH_MAX_МСК_ПУШКИНО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:03:56' union all
select 'FRESH_MAX_МСК_РЕУТОВ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:03:56' union all
select 'FRESH_MAX_МСК_САВЕЛОВСКИЙ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:23:16' union all
select 'FRESH_MAX_МСК_САЛАРЬЕВО','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:30:17' union all
select 'FRESH_MAX_МСК_ТРОИЦК','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','3:54:07' union all
select 'FRESH_MAX_МСК_ТЮМЕНСКИЙ','FRESH_MAX_ТВЕРЬ_КАЛИНИНА','4:08:08';