package com.example.advantumconverter.enums;

public enum State {

    FREE,

    CONVERT_FILE_COFIX,

    CONVERT_FILE_BOGORODSK,

    CONVERT_FILE_SAMOKAT,

    CONVERT_FILE_LENTA,

    CONVERT_FILE_DOMINOS,

    ADMIN_SETTING_WAIT_USERNAME, ADMIN_SETTING_WAIT_COMPANY, ADMIN_SETTING_WAIT_ROLE,

    FAQ_WAIT_QUESTION
}
