package com.example.advantumconverter.enums;

public enum State {

    FREE,

    CONVERT_FILE_COFIX,

    CONVERT_FILE_BOGORODSK,

    CONVERT_FILE_SAMOKAT,

    CONVERT_FILE_LENTA,

    CONVERT_FILE_OZON,

    CONVERT_FILE_METRO,

    CONVERT_FILE_DOMINOS,

    CONVERT_FILE_AGROPROM,

    CONVERT_FILE_BOOKER,

    CONVERT_FILE_AGROPROM_DETAIL,

    ADMIN_SETTING_WAIT_USERNAME, ADMIN_SETTING_WAIT_COMPANY, ADMIN_SETTING_WAIT_ROLE,

    FAQ_WAIT_QUESTION,

    SUPPORT_WAIT_SHOW_TASK, SUPPORT_WAIT_MODE_WORK, SUPPORT_WAIT_CHOOSE_TASK, SUPPORT_WAIT_RESOLVE_MESSAGE, SUPPORT_WAIT_RESOLVE_TASK, SUPPORT_WAIT_SHOW_TASK_INFO,

    HISTORY_WAIT_USER, HISTORY_WAIT_COMPANY,

    CANCEL
}
